### ISSUE TITLE
Logic doesn't support Kyverno Auto-Gen Rules

### ISSUE THREAD

**Issue by rayterrill** [ckotzbauer/kyverno-test-action#502]
The current logic for building the `results` section of the test file doesn't support Kyverno Auto-Gen Rules (https://kyverno.io/docs/writing-policies/autogen/). The current logic looks for an exact match between the rules file kind and what's in the manifest.

I forked the repo and took a crack at adding support with something like this (note the new autogenResources section and the adjusted includes line):
```
const generateTestFile = async function (policies: ClusterPolicy[], resources: Resource[]): Promise<void> {
  const test: Test = {
    name: "kyverno-test",
    resources: ["resources.yaml"],
    policies: ["rules.yaml"],
    results: [],
  };

  const autogenResources = ["deployment", "daemonset", "statefulset", "job", "cronjob"];

  for (const policy of policies) {
    for (const rule of policy.spec.rules) {
      for (const resource of resources) {
        //const includes = rule?.match?.resources?.kinds?.includes(resource.kind) ?? false;
        const includes = (rule?.match?.resources?.kinds?.includes(resource.kind) || autogenResources.includes(resource.kind.toLowerCase())) ?? false;
        const excludes = rule?.exclude?.resources?.kinds?.includes(resource.kind) ?? false;

        if (includes && !excludes) {
          test.results.push({
            policy: policy.metadata.name,
            rule: rule.name,
            resource: resource.metadata.name,
            kind: resource.kind,
            result: "pass",
          });
        }
      }
    }
  }

  const testContent = dump(test, { indent: 2 });
  core.debug("Generated kyverno-test.yaml:");
  core.debug(testContent);
  await promisify(writeFile)("/tmp/kyverno-test/kyverno-test.yaml", testContent);
};
```

This works locally for me, but my typescript is quite rusty - would love to get support in here for this.

**Comment by ckotzbauer** [comment]
Hi @rayterrill,
thanks for the issue. When I understand your use-case correctly, you want to define policies for pods and then pass in resources like Deployments, StatefulSets, ...

There's already a autogen-logic in this action included: https://github.com/ckotzbauer/kyverno-test-action/blob/main/src/rule-files.ts#L63
For "Pod" rules with `pattern` or `anyPattern` there are rules for DaemonSets, Deployments, StatefulSets, Jobs and CronJobs generated and checked automatically. So there should be no need to add this additional check.

Can you please share a sample of a resource and a rule where the logic did not execute the expected check?
Thanks!

**Comment by rayterrill** [comment]
I couldnt get this working, and now I'm running into this:
```
Download kyverno from url: https://github.com/kyverno/kyverno/releases/download/v1.9.5/kyverno-cli_v1.9.5_linux_x86_64.tar.gz
Extract kyverno archive: /home/runner/work/_temp/9d8bdf32-[12](https://github.com/StackEngLabs/raytest/actions/runs/6643586386/job/18050951819?pr=6#step:6:13)da-4a0c-aebb-7e7a09591ed8
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/5d6b5901-aee4-4ddc-8fb4-9639ff71d756 -f /home/runner/work/_temp/9d8bdf32-12da-4a0c-aebb-7e7a09591ed8
Error: EISDIR: illegal operation on a directory, read
```

We ended up going a different direction - closing.
